PROVIDER_META = {
    # Free, no key
    'binance_klines': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; weight/rate limits apply.'},
    'coingecko_market_chart': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Strict free rate limits; backoff recommended.'},
    'yahoo_price': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Free; can throttle or block heavy scraping.'},
    'exchangerate_host_timeseries': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': Low:=False if False else False, 'notes': 'Free; no key required.'},
    'worldbank_indicator': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free; no key required.'},
    'owid_covid_country': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free CSV; no key.'},
    'usgs_earthquakes': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free; no key required.'},
    'open_meteo_hourly': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free; no key required.'},
    'bitfinex_candles': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'kraken_ohlc': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'bitstamp_ohlc': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'wikipedia_pageviews': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Free; REST limits for heavy usage.'},
    'coinpaprika_historical': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Free; REST limits apply.'},
    'fear_greed_index': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free; no key.'},
    'coinbase_candles': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Free; add User-Agent header.'},
    'kucoin_candles': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'okx_candles': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'huobi_klines': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'coindesk_bpi': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': Low:=False if False else False, 'notes': 'Free; no key.'},
    'hn_stories_count': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free; no key.'},
    'ecb_fx_daily': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free CSV; no key.'},
    'bybit_klines': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'ftx_archive_klines': {'requires_api_key': False, 'optional_api_key': True, 'rate_limited': True, 'notes': 'Via CryptoCompare aggregator; free limited without key.'},
    'coinmetrics_community': {'requires_api_key': True, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Community API requires API key.'},
    'glassnode_metric': {'requires_api_key': True, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Requires API key.'},
    'cryptocompare_hourly': {'requires_api_key': False, 'optional_api_key': True, 'rate_limited': True, 'notes': 'Free limited; API key increases limits.'},
    'alphavantage_fx_daily': {'requires_api_key': True, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Requires free API key.'},
    'fred_series': {'requires_api_key': True, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Requires free API key.'},
    'coinbase_best_bid_ask': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Free; endpoint returns latest snapshot.'},
    'theta_network_price': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Via Coingecko; rate limited.'},
    'cot_futures': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'CFTC CSV mirror; free.'},
    'us_treasury_daily': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Treasury CSV; free.'},
    'binance_funding_rate': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'binance_open_interest': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Public REST; limits apply.'},
    'santiment_metric': {'requires_api_key': True, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Requires API key.'},
    'coinapi_trades': {'requires_api_key': True, 'optional_api_key': False, 'rate_limited': True, 'notes': 'Requires API key.'},
    'messari_asset_timeseries': {'requires_api_key': False, 'optional_api_key': True, 'rate_limited': True, 'notes': 'Free tier available; API key recommended.'},
    'defillama_tvl': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free; no key.'},
    'cboe_vix_daily': {'requires_api_key': False, 'optional_api_key': False, 'rate_limited': False, 'notes': 'Free CSV; no key.'},
}


